package-lock.json
package.json
pages/_app.js
pages/_document.js
pages/index.js

Description
-----------
Antd is a powerful and very complete component library for React. This
patch leverages it to provide a clear design for the application.
Checklist
---------
Fixes scrapd/scrapdviz#13

Use Antd components for the design

---

components/scrapd-grid.js
redux/store.js

Description
-----------
When dates are selected, the date boundaries are now added to the redux
store.
Checklist
---------

Add date filter data to redux store

---

components/scrapd-ethnicity-graph.js
package-lock.json
package.json
pages/index.js
redux/saga.js

Description
-----------
Uses `react-vis` to create a pie chart representing the ethnicity
distribution of the fatalities.
Drive-by:
* Install React Vis
Checklist
---------
Fixes scrapd/scrapdviz#9

Add ethnicity distribution graph

---

components/scrapd-gender-graph.js
pages/index.js

Description
-----------
Shows the gender distribution in a pie chart.
Checklist
---------
Fixes scrapd/scrapdviz#7

Add gender distribution graph

---

components/scrapd-fatality-counter.js
mock-api/mock-data.js
pages/index.js

Description
-----------
Adds a fatality counter to the graph section.
Checklist
---------
Fixes scrapd/scrapdviz#6

Add a fatality counter

---

components/scrapd-age-graph.js
components/scrapd-grid.js
pages/index.js

Description
-----------
Arrange the data in bucket of 10 years then render the pis chart.
Checklist
---------
Fixes scrapd/scrapdviz#8

Add age distribution graph

---

components/scrapd-age-graph.js
components/scrapd-ethnicity-graph.js
components/scrapd-fatality-counter.js
components/scrapd-gender-graph.js
pages/index.js

Description
-----------
The graphs are displayed in their own sections where the horizontal
space is handled dynamically, and where the line automatically wrap if
there is not enough space to display the elements.
Checklist
---------
Fixes scrapd/scrapdviz#28

Encapsulate the graphs in a flexbox div

---

redux/saga.js

Description
-----------
Adds logic to the saga to filter the dates it retrieves. As we won't have
any API at first, we will simply retrieve the full data set when the
page loads for the first time (it will be cached by the service worker
after that), and filter out the information we don't want to display.
Checklist
---------
Fixes scrapd/scrapdviz#27

Add date filtering

---

components/scrapd-grid.js
redux/store.js

Description
-----------
Drive-by:
* Adds the full data set into the mock api data.
Checklist
---------
Fixes scrapd/scrapdviz#35

Load data of the current month by default

---

components/scrapd-grid.js
pages/index.js

Description
-----------
The table has a minimum size of 1024px wide, therefore cannot be
displayed on a mobile device.
Drive-by:
* Fix the spacing around the graphs.
Checklist
---------
Fixes scrapd/scrapdviz#25

Hide table in mobile mode

---

redux/saga.js

Description
-----------
Retrieves the real data set instead of using the mock data.
Checklist
---------
Fixes scrapd/scrapdviz#41

Fetch the data set from GitHub

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
pages/index.js

Description
-----------
This version is functional, but does not import the `antd` CSS for some
reason. In spite of that the data is retrieved and the graphs are
displayed correctly. As a result we can start using it as a baseline for
the deployments.
Checklist
---------

Prepare the preview version

---

.circleci/config.yml
package.json

Description
-----------
Checklist
---------

Fix deployment pipeline

---

package.json
tools/deploy.sh

Description
-----------
Fixes the deploy instructions and externalize them to a dedicated script.
Checklist
---------
Fixes scrapd/scrapdviz#49

Fix deploy script

---

components/scrapd-age-graph.js

Description
-----------
The age groups were updated to be more relevant. The source for the new
classification is
http://www.pgagroup.com/standardized-survey-classifications.html.
Checklist
---------

Implement better age buckets

---

components/scrapd-age-graph.js
components/scrapd-grid.js
components/scrapd-pie-graph.js
package-lock.json
pages/index.js

Description
-----------
Creates a generic pie chart component to make it easier to visualize a
certain attribute of a fatality, as well as to make the chart style more
consistent.
This patch also shows the percentages of each category under the labels.
Uses `npm audit fix` to update the vulnerable dependencies.
Checklist
---------
Fixes scrapd/scrapdviz#22
Fixes scrapd/scrapdviz#23

Create a generic pie chart component

---

components/scrapd-age-graph.js
components/scrapd-generic-pie-chart.js
package-lock.json
package.json

- Breaking change (fix or feature that would cause existing functionality to change)
Description
-----------
Victory is one of the visualization library recommended by ant design,
therefore I decided to use it. It renders pretty nicely and give the
ability to add a legend to the graphs.
The downside is that there is no dynamic placement of the elements.
Checklist
---------

Use Victory to render the graphs

---

components/scrapd-fatality-counter.js
package-lock.json

Description
-----------
The font size of the fatality counter will vary according to the number
of fatalities (to fit in the card).
Also, when displayed in mobile mode, the fatality counter will be placed
first instead of last.
Checklist
---------
Fixes scrapd/scrapdviz#54

Make fatality counter font responsive

---

components/scrapd-grid.js

Description
-----------
Adds the options to sort the table data by date (default behavior) or by
crash number.
Checklist
---------
Fixes scrapd/scrapdviz#53

Sort table data

---

components/scrapd-age-graph.js
components/scrapd-fatality-counter.js
components/scrapd-generic-pie-chart.js
components/scrapd-pie-graph.js

Description
-----------
* Put the title of the graphs in the box, centered, just above the pie.
* Add undefined age category
* Adjust the legend to be better vertically centered
* Fix attribute casing
Checklist
---------

Makes the graphs even better

---

components/scrapd-grid.js

Description
-----------
Sets the default dates in the Date Picker from the default values in the
redux store.
Checklist
---------
Fixes scrapd/scrapdviz#38

Set default date on load in Date picker

---

next.config.js
package-lock.json
package.json

Description
-----------
Updates some plugin options and stop using PurifyCSS in order to make
the static build succeed.
* Update configuration package.json
* Disable the tests as
* they were useless
* they stopped working with the new build options
Checklist
---------
Fixes scrapd/scrapdviz#43

Fix the build

---

.circleci/config.yml
components/scrapd-fatality-counter.js
components/scrapd-map.js
package-lock.json
package.json
pages/index.js
redux/saga.js
tools/deploy.sh

Description
-----------
Adds a basic map clustering the fatalities.
Drive-by:
* Update the deploy script to use `ghp-import` to publish the site.
Checklist
---------
Fixes #scrapd/scrapdviz/24

Add map with clustering support

---

tools/deploy.sh

Description
-----------
Ensures the site is deploy correctly when the site run. In addition, the
script now auto-detects which remote to deploy to.
Checklist
---------
Fixes scrapd/scrapdviz#67

Fix the deploy script

---

components/scrapd-grid.js

Description
-----------
The deploy key was incorrectly setup.
Drive-by:
* Fix typo in clipboard notification.
Checklist
---------

Fix deployment

---

components/scrapd-grid.js

Description
-----------
Adds a quick filter to the date picker to retrieve all the available
fatalities.
Checklist
---------
Fixes scrapd/scrapdviz#66

Add "all" quick filter

---

.circleci/config.yml

Description
-----------
Deploys the application only when we tag the repository.
Checklist
---------
Fixes scrapd/scrapdviz#73

Update CircleCI config to deploy on tag

---

components/scrapd-grid.js
pages/index.js

Description
-----------
This patch gives the user the ability to click on the case number and to
be redirected to the corresponding APD report.
Drive-by:
* Changes the size of the table from "big" to "medium".
Checklist
---------
Fixes scrapd/scrapdviz#71

Link a fatality to its APD report

---

__mocks__/fileMock.js
__mocks__/styleMock.js
package.json
tests/index.test.js

Setup working config for Jest tests
Fixes scrapd/scrapdviz#

Test config setup

---

CHANGELOG.md
components/scrapd-grid.js
pages/index.js

Description
-----------
Adds icons pointing to:
* The ScrAPD GitHub organization
* The Ant Design framework
* The info@scrapd.org email
Drive-by:
* Adds a Changelog.
Checklist
---------
-  [X] I have updated the documentation accordingly
Fixes scrapd/scrapdviz#75

Add social media icons

---

components/scrapd-age-graph.js

Description
-----------
The age distribution graph has too many groups and they are not really
representative of anything. This patch classifies the fatalities amongst
5 meaningful categories.
Checklist
---------
Fixes scrapd/scrapdviz#87

Use better age groups

---

components/scrapd-grid.js
components/scrapd-map.js
redux/saga.js

Description
-----------
Updates the date picker presets with more useful values.
Checklist
---------
Fixes scrapd/scrapdviz#77

Update date picker presets

---

components/scrapd-generic-bar-chart.js
components/scrapd-month-graph.js
pages/index.js

Description
-----------
Adds a graph showing the evolution of the fatalities month by month.
Checklist
---------
Fixes scrapd/scrapdviz#83

Add month distribution graph

---

components/scrapd-weekday-graph.js
pages/index.js

Description
-----------
Adds a graph showing the fatalities for each day of the week.
Checklist
---------
Fixes scrapd/scrapdviz#84

Add a weekday distribution graph

---

CHANGELOG.md
components/scrapd-time-graph.js
pages/index.js

Description
-----------
Adds a graph showing the fatalities per hours, grouped in meaningful
buckets.
Checklist
---------
Fixes scrapd/scrapdviz#85

Add a time of day distribution graph

---

components/scrapd-month-graph.js
components/scrapd-weekday-graph.js
redux/store.js

Clean up the bar graphs.
- Breaking change (fix or feature that would cause existing functionality to change)
Description
-----------
Checklist
---------
Fixes scrapd/scrapdviz#

Clean bar graphs

---

CHANGELOG.md

Description
-----------
Prepares the 0.2.4 release.
Checklist
---------

Prepare 0.2.4 release

---

components/scrapd-grid.js

**X New feature (non-breaking change which adds functionality)**
- Breaking change (fix or feature that would cause existing functionality to change)
Description
-----------
This change solves Issue #15 .
Checklist
---------
Fixes scrapd/scrapdviz#
https://github.com/scrapd/scrapdviz/issues/15

Added a functioning download button for Issue #15

---

components/layout.js
components/scrapd-age-graph.js
components/scrapd-controls.js
components/scrapd-grid.js
components/scrapd-map.js
components/scrapd-pie-graph.js
components/scrapd-time-graph.js
package-lock.json
pages/_app.js
pages/archives.js
redux/store.js

Description
-----------
Adds a menu allowing the user to select between the 'APD' view and the
'Archives' view.
* Create a layout component
* Split the main view into more components
* Order imports
Checklist
---------
Fixes scrapd/scrapdviz#98

Add the archive view

---

components/scrapd-year-graph.js
pages/archives.js

Description
-----------
Adds a graph to compare the full years together.
Checklist
---------
Fixes scrapd/scrapdviz#82

Add Year Over Year graph

---

components/fatality-counter/__tests__/__snapshots__/component.test.js.snap
components/fatality-counter/component.js

Description
-----------
Our data set contains axtually crash information, not fatality
information. Therefore the counter was misleading.
Checklist
---------
-  [X] I have written unit tests
Fixes scrapd/scrapdviz#99

Counter counts crashes not fatalities

---

pages/archives.js

Description
-----------
Adds a graph showing the crash distribution by transportation mode.
Checklist
---------
Fixes scrapd/scrapdviz#101

Add a transportation mode graph

---

components/scrapd-cause-graph.js
pages/archives.js

Description
-----------
Adds a graph representing the crashes by cause.
Checklist
---------
Fixes scrapd/scrapdviz#100

Add a cause distribution graph

---

CHANGELOG.md

Description
-----------
Updates the Changelog.
Checklist
---------
-  [X] I have updated the documentation accordingly

Update the Cxhangelog

---

components/scrapd-cause-graph.js

Description
-----------
Crash causes can actually be combined (i.e. someone can be speeding and
drunk at the same time).
Checklist
---------

Crash causes are not mutually exclusive

---

contributors.md

Description
-----------
Adds a list of all the people who contributed to this project.
Checklist
---------

Add contributor list

---

components/scrapd-controls/component.js

Description
-----------
> This is simply an example of utilizing `ref`. Not necessarily a merge.
Instead of creating & removing an anchor tag to download a file create an anchor tag at the top level & hide it with CSS, and attach to it a `ref`. When the user clicks download the `ref` is simply called.

How to: using 'ref'

---

CHANGELOG.md
components/scrapd-apd-view/component.js
components/scrapd-apd-view/container.js
components/scrapd-archive-view/component.js
components/scrapd-archive-view/container.js
components/scrapd-controls/component.js
components/scrapd-controls/container.js
components/scrapd-no-data-alert/component.js
pages/archives.js
pages/index.js
redux/saga.js
redux/store.js

Description
-----------
Improves the data flow by thinking more in the React way.
* Adds no data alert message
* Adds more date picker presets
* Adds APD view component.
Checklist
---------

Improve the data flow.

---

components/scrapd-apd-view/component.js
components/scrapd-grid/component.js

Description
-----------
Adds the grid showing the fatalities to the APD view.
Checklist
---------

Add data grid to APD view

---

components/scrapd-layout.js
redux/store.js

Description
-----------
When clicking on a tab, the selected tab was always reset to the default
tab. This patches fixes this issues by storing the current tab value
into the redux store.
Drive-by:
* Remove useless code.
Checklist
---------

Fix tab selection

---

components/scrapd-map/component.js

Description
-----------
Adjusts the sizes and the colors of the clusters based on the number of
crashes they represent.
Checklist
---------
Fixes scrapd/scrapdviz#127
Fixes scrapd/scrapdviz#129

Adjust map clusters

---

components/scrapd-map/component.js
package-lock.json
package.json

Description
-----------
The marker now use an icon to represent the type of crash. Each type
also has a color.
* Use FontAwesome for the icons
* Use better colors
Checklist
---------
Fixes scrapd/acrapdviz#128

Add crash type icons to map markers

---

components/scrapd-map/component.js

Description
-----------
Invalid coordinates prevent markers to render, therefore the map does
not display anything.
This patch filters out the invalid coordinates from the data set.
Checklist
---------
Fixes scrapd/scrapdviz#97

Ignore invalid coordinates

---

components/scrapd-grid/component.js

Description
-----------
Renames the date and time columns as they were confusing for the users.
They were not sure whether they meant the date/time of the crash or the
date/time of the report.
Checklist
---------
Fixes scrapd/scrapdviz#120

Rename date/time columns

---

components/scrapd-no-data-alert/component.js

Description
-----------
Clarifies the warning message mentioning that there is no data to show
for the selected dates.
Checklist
---------
Fixes scrapd/scrapdviz#122

Writes a better warning message

---

CHANGELOG.md
package.json

Description
-----------
Prepares the 0.4.0 release.
Checklist
---------

Prepare for 0.4.0 release

---

components/scrapd-home-section/component.js
components/scrapd-home-view/component.js

Working on this long term with Abhra to finalize and polish the home page.

Scrapd home section

---

.gitignore
components/scrapd-hero/component.js
components/scrapd-home-view/component.js

Adding a component for the Hero Image instead of it being one large file along the boxes underneath it.

Add Hero Component

---

components/scrapd-hero/component.js
components/scrapd-home-view/component.js

Refactored the CSS in the Hero component. Was not using Emotion.js initially, now it is.

Scrapd hero css in js

---

components/scrapd-home-section/component.js
components/scrapd-home-view/component.js
components/scrapd-layout.js

Description
-----------
Updates the content of the home page to provide more relevant
information to the users.
Checklist
---------

Update home page content

---

CHANGELOG.md

Description
-----------
Update CHANGELOG.md
Checklist
---------

Prepare for 1.0.0 release

---

components/scrapd-home-view/component.js

Description
-----------
Ensures the images in the home page sections alternate side.
Checklist
---------

Fix alternate images on home page

---

components/scrapd-archive-view/component.js
components/scrapd-cause-graph/component.js
components/scrapd-layout.js
components/scrapd-year-graph/component.js

Description
-----------
Fixes the archive view graphs by adjusting the name of the attributes
used for rendering the graphs.
Drive-by:
* Fix the proptypes for scrapd-layout.
Checklist
---------

Fix archive view graphs

---

components/scrapd-grid/component.js

Description
-----------
The report link was broken as it used the capitalized attribute from the ScrAPD 2 format.
Checklist
---------

Fix report link in grid in APD view

---

next.config.js
package.json
pages/_app.js
pages/_document.js

Description
-----------
Google tag is not receiving any data being the NextJS export always
returns `NODE_ENV != production`. This patch solves this problem.
Checklist
---------

Fix Google Tag

---

components/scrapd-layout.js
redux/store.js

Description
-----------
When accessing the site via URL, the tabs do not necessarily reflect the
right location.

Fix tab vs url bug

---

CHANGELOG.md

Prepares the codebase for `1.3.0` release.
Description
-----------
Checklist
---------

Prepare 1.3.0 release
